### ISSUE TITLE
RenAIssance Notebook

### ISSUE THREAD

**Issue by BoGGoG** [ML4SCI/DeepLearnHackathon#15]
Cool stuff!
Some points:

- [x] cell for resizing images not working, because `new_size` is not defined
<img width="941" alt="image" src="https://github.com/ML4SCI/DeepLearnHackathon/assets/7156434/9c60f52d-1338-4f92-b50c-acdfc90101c2">

- [x] do you really want to keep all the data peprocessing that generates the images or would it be better to just provide the already chopped up and finished images?
- [x] can you also add the notebook to the repo?
- [x] when I simply ran the notebook on colab I got vastly worse results (basically useless). Did I just get unlucky?

![image](https://github.com/ML4SCI/DeepLearnHackathon/assets/7156434/3c76ff50-9cd3-40e6-aa9c-8b6104e6c673)

**Comment by Shashankss1205** [comment]
Sorry, I forgot to remove the new_size variable as input, because I made it as a default variable for that function. It's corrected now.
1) do you really want to keep all the data peprocessing that generates the images or would it be better to just provide the already chopped up and finished images?
It was told by Mr. Sergei to provide pre-processing steps as the input is a pdf file not an image folder
2) can you also add the notebook to the repo?
I will add it by evening after making it a little more readable
3) when I simply ran the notebook on colab I got vastly worse results (basically useless). Did I just get unlucky?
You can increase the number of epochs 10 folds from 20 to 200 for getting a little better and understandable results, I will change that too in the notebook.

**Comment by Shashankss1205** [comment]
![samplerun](https://github.com/ML4SCI/DeepLearnHackathon/assets/123410790/5e25ea5b-4742-4ce1-b88f-b91136801638)
Is this workable?
